name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - name: Run Test
        run: make test
        shell: bash
